import { EstimateItem } from './crmData';

export interface EstimateTemplate {
  id: string;
  name: string;
  description: string;
  category: 'water' | 'fire' | 'mold' | 'storm' | 'general' | 'roofing' | 'siding';
  items: Omit<EstimateItem, 'id'>[];
  terms?: string;
  notes?: string;
}

export const ESTIMATE_TEMPLATES: EstimateTemplate[] = [
  {
    id: 'water-extraction',
    name: 'Water Damage - Emergency Extraction',
    description: 'Emergency water extraction and drying services',
    category: 'water',
    items: [
      { description: 'Emergency Response & Assessment', quantity: 1, unit: 'ea', unitPrice: 350, total: 350 },
      { description: 'Water Extraction (per room)', quantity: 3, unit: 'room', unitPrice: 450, total: 1350 },
      { description: 'Dehumidifier Setup (per unit)', quantity: 2, unit: 'ea', unitPrice: 125, total: 250 },
      { description: 'Air Mover Setup (per unit)', quantity: 4, unit: 'ea', unitPrice: 75, total: 300 },
      { description: 'Moisture Monitoring (3 days)', quantity: 3, unit: 'day', unitPrice: 150, total: 450 },
    ],
    terms: 'Payment due upon completion. Insurance claims accepted.',
    notes: 'Equipment rental included for up to 3 days. Additional days billed separately.',
  },
  {
    id: 'fire-restoration',
    name: 'Fire Damage - Full Restoration',
    description: 'Complete fire damage restoration including cleanup and repairs',
    category: 'fire',
    items: [
      { description: 'Emergency Board-Up & Securing', quantity: 1, unit: 'ea', unitPrice: 800, total: 800 },
      { description: 'Soot & Smoke Removal', quantity: 1500, unit: 'sqft', unitPrice: 3.5, total: 5250 },
      { description: 'Odor Removal Treatment', quantity: 1, unit: 'ea', unitPrice: 1200, total: 1200 },
      { description: 'Content Pack-Out & Storage', quantity: 1, unit: 'ea', unitPrice: 2500, total: 2500 },
      { description: 'Structural Cleaning', quantity: 1, unit: 'ea', unitPrice: 3500, total: 3500 },
    ],
    terms: 'Deposit required. Insurance billing available.',
    notes: 'Includes initial assessment and detailed scope of work.',
  },
  {
    id: 'mold-remediation',
    name: 'Mold Remediation',
    description: 'Professional mold inspection and remediation',
    category: 'mold',
    items: [
      { description: 'Mold Inspection & Testing', quantity: 1, unit: 'ea', unitPrice: 500, total: 500 },
      { description: 'Containment Setup', quantity: 1, unit: 'ea', unitPrice: 800, total: 800 },
      { description: 'Mold Removal & Treatment', quantity: 500, unit: 'sqft', unitPrice: 8, total: 4000 },
      { description: 'HEPA Air Filtration', quantity: 3, unit: 'day', unitPrice: 200, total: 600 },
      { description: 'Post-Remediation Testing', quantity: 1, unit: 'ea', unitPrice: 400, total: 400 },
    ],
    terms: 'Payment due upon completion. Certified mold remediation.',
    notes: 'All work performed by certified technicians following EPA guidelines.',
  },
  {
    id: 'storm-damage',
    name: 'Storm Damage - Roof & Exterior',
    description: 'Storm damage assessment and emergency repairs',
    category: 'storm',
    items: [
      { description: 'Emergency Roof Tarping', quantity: 1, unit: 'ea', unitPrice: 1200, total: 1200 },
      { description: 'Debris Removal', quantity: 1, unit: 'ea', unitPrice: 800, total: 800 },
      { description: 'Roof Inspection & Assessment', quantity: 1, unit: 'ea', unitPrice: 350, total: 350 },
      { description: 'Window Board-Up', quantity: 4, unit: 'ea', unitPrice: 150, total: 600 },
      { description: 'Interior Water Damage Mitigation', quantity: 1, unit: 'ea', unitPrice: 1500, total: 1500 },
    ],
    terms: 'Insurance claims accepted. Emergency services available 24/7.',
    notes: 'Includes photo documentation for insurance claims.',
  },
  {
    id: 'basement-flood',
    name: 'Basement Flood Cleanup',
    description: 'Complete basement water removal and restoration',
    category: 'water',
    items: [
      { description: 'Basement Water Extraction', quantity: 1, unit: 'ea', unitPrice: 1500, total: 1500 },
      { description: 'Sewage Cleanup (if applicable)', quantity: 1, unit: 'ea', unitPrice: 2000, total: 2000 },
      { description: 'Dehumidification (5 days)', quantity: 5, unit: 'day', unitPrice: 200, total: 1000 },
      { description: 'Antimicrobial Treatment', quantity: 800, unit: 'sqft', unitPrice: 2, total: 1600 },
      { description: 'Carpet Removal & Disposal', quantity: 800, unit: 'sqft', unitPrice: 1.5, total: 1200 },
    ],
    terms: 'Payment due upon completion. Insurance billing available.',
    notes: 'Category 3 water (sewage) requires additional safety protocols.',
  },
  {
    id: 'kitchen-fire',
    name: 'Kitchen Fire Restoration',
    description: 'Kitchen fire damage cleanup and restoration',
    category: 'fire',
    items: [
      { description: 'Kitchen Fire Cleanup', quantity: 1, unit: 'ea', unitPrice: 2500, total: 2500 },
      { description: 'Smoke Odor Removal', quantity: 1, unit: 'ea', unitPrice: 800, total: 800 },
      { description: 'Cabinet Cleaning & Restoration', quantity: 1, unit: 'ea', unitPrice: 1200, total: 1200 },
      { description: 'Appliance Cleaning', quantity: 4, unit: 'ea', unitPrice: 150, total: 600 },
      { description: 'Wall & Ceiling Cleaning', quantity: 300, unit: 'sqft', unitPrice: 4, total: 1200 },
    ],
    terms: 'Insurance claims accepted.',
    notes: 'Includes detailed photo documentation and scope of work.',
  },
  {
    id: 'sewage-backup',
    name: 'Sewage Backup Cleanup',
    description: 'Emergency sewage cleanup and sanitization',
    category: 'water',
    items: [
      { description: 'Emergency Sewage Extraction', quantity: 1, unit: 'ea', unitPrice: 2500, total: 2500 },
      { description: 'Biohazard Cleanup', quantity: 1, unit: 'ea', unitPrice: 1800, total: 1800 },
      { description: 'Antimicrobial Treatment', quantity: 600, unit: 'sqft', unitPrice: 3, total: 1800 },
      { description: 'Affected Materials Removal', quantity: 1, unit: 'ea', unitPrice: 1500, total: 1500 },
      { description: 'Air Scrubbing & Deodorization', quantity: 3, unit: 'day', unitPrice: 250, total: 750 },
    ],
    terms: 'Payment due upon completion. Category 3 water damage.',
    notes: 'All work performed following IICRC S500 standards for Category 3 water.',
  },
  {
    id: 'attic-mold',
    name: 'Attic Mold Remediation',
    description: 'Attic mold removal and prevention',
    category: 'mold',
    items: [
      { description: 'Attic Mold Inspection', quantity: 1, unit: 'ea', unitPrice: 400, total: 400 },
      { description: 'Mold Remediation', quantity: 800, unit: 'sqft', unitPrice: 6, total: 4800 },
      { description: 'Insulation Removal & Disposal', quantity: 800, unit: 'sqft', unitPrice: 2, total: 1600 },
      { description: 'Antimicrobial Treatment', quantity: 800, unit: 'sqft', unitPrice: 1.5, total: 1200 },
      { description: 'Ventilation Improvement', quantity: 1, unit: 'ea', unitPrice: 1200, total: 1200 },
    ],
    terms: 'Payment due upon completion. Warranty on remediation work.',
    notes: 'Includes moisture source identification and prevention recommendations.',
  },
  {
    id: 'commercial-water',
    name: 'Commercial Water Damage',
    description: 'Large-scale commercial water damage restoration',
    category: 'water',
    items: [
      { description: 'Emergency Response (24/7)', quantity: 1, unit: 'ea', unitPrice: 1500, total: 1500 },
      { description: 'Water Extraction (Large Area)', quantity: 5000, unit: 'sqft', unitPrice: 2, total: 10000 },
      { description: 'Industrial Dehumidifiers', quantity: 6, unit: 'ea', unitPrice: 300, total: 1800 },
      { description: 'Air Movers (Commercial)', quantity: 12, unit: 'ea', unitPrice: 100, total: 1200 },
      { description: 'Daily Monitoring (5 days)', quantity: 5, unit: 'day', unitPrice: 400, total: 2000 },
    ],
    terms: 'Commercial insurance billing. Net 30 payment terms.',
    notes: 'After-hours work available. Minimal business disruption guaranteed.',
  },
  {
    id: 'general-restoration',
    name: 'General Property Restoration',
    description: 'Standard property restoration services',
    category: 'general',
    items: [
      { description: 'Initial Assessment & Inspection', quantity: 1, unit: 'ea', unitPrice: 250, total: 250 },
      { description: 'Labor (per hour)', quantity: 8, unit: 'hr', unitPrice: 85, total: 680 },
      { description: 'Materials & Supplies', quantity: 1, unit: 'ea', unitPrice: 500, total: 500 },
      { description: 'Equipment Rental', quantity: 3, unit: 'day', unitPrice: 150, total: 450 },
      { description: 'Disposal & Cleanup', quantity: 1, unit: 'ea', unitPrice: 400, total: 400 },
    ],
    terms: 'Payment due upon completion.',
    notes: 'Customizable based on specific project needs.',
  },
  {
    id: 'asphalt-roof',
    name: 'Asphalt Shingle Roof Replacement',
    description: 'Complete asphalt shingle roof replacement with all materials',
    category: 'roofing',
    items: [
      { description: 'Roof Tear-Off & Disposal', quantity: 25, unit: 'sq', unitPrice: 125, total: 3125 },
      { description: 'Architectural Asphalt Shingles (30-year)', quantity: 25, unit: 'sq', unitPrice: 350, total: 8750 },
      { description: 'Synthetic Underlayment', quantity: 25, unit: 'sq', unitPrice: 45, total: 1125 },
      { description: 'Ice & Water Shield (valleys/eaves)', quantity: 8, unit: 'roll', unitPrice: 85, total: 680 },
      { description: 'Drip Edge (aluminum)', quantity: 180, unit: 'lf', unitPrice: 3.5, total: 630 },
      { description: 'Ridge Vent', quantity: 40, unit: 'lf', unitPrice: 12, total: 480 },
      { description: 'Ridge Cap Shingles', quantity: 3, unit: 'bundle', unitPrice: 65, total: 195 },
      { description: 'Roof Vents (static)', quantity: 4, unit: 'ea', unitPrice: 85, total: 340 },
      { description: 'Pipe Boots/Flashings', quantity: 6, unit: 'ea', unitPrice: 45, total: 270 },
      { description: 'Valley Flashing (metal)', quantity: 30, unit: 'lf', unitPrice: 8, total: 240 },
      { description: 'Starter Shingles', quantity: 180, unit: 'lf', unitPrice: 2.5, total: 450 },
      { description: 'Roofing Nails & Fasteners', quantity: 1, unit: 'lot', unitPrice: 250, total: 250 },
      { description: 'Labor - Installation', quantity: 25, unit: 'sq', unitPrice: 180, total: 4500 },
      { description: 'Dumpster & Cleanup', quantity: 1, unit: 'ea', unitPrice: 450, total: 450 },
    ],
    terms: '50% deposit required. Balance due upon completion. Warranty: 10-year workmanship, 30-year manufacturer.',
    notes: 'Price based on 2,500 sqft roof (25 squares). Includes all materials, labor, permits, and cleanup. Does not include structural repairs or decking replacement.',
  },
  {
    id: 'corrugated-metal-roof',
    name: 'Corrugated Metal Roof Installation',
    description: 'Corrugated metal roofing system installation',
    category: 'roofing',
    items: [
      { description: 'Roof Tear-Off & Disposal (if needed)', quantity: 25, unit: 'sq', unitPrice: 125, total: 3125 },
      { description: 'Corrugated Metal Panels (29 gauge)', quantity: 2600, unit: 'sqft', unitPrice: 4.5, total: 11700 },
      { description: 'Synthetic Underlayment', quantity: 25, unit: 'sq', unitPrice: 45, total: 1125 },
      { description: 'Metal Roof Purlins/Strapping', quantity: 2600, unit: 'sqft', unitPrice: 1.2, total: 3120 },
      { description: 'Eave Trim (metal)', quantity: 180, unit: 'lf', unitPrice: 6, total: 1080 },
      { description: 'Rake Trim (metal)', quantity: 120, unit: 'lf', unitPrice: 6, total: 720 },
      { description: 'Ridge Cap (metal)', quantity: 40, unit: 'lf', unitPrice: 15, total: 600 },
      { description: 'Valley Flashing (metal)', quantity: 30, unit: 'lf', unitPrice: 12, total: 360 },
      { description: 'Closure Strips (foam)', quantity: 180, unit: 'lf', unitPrice: 2, total: 360 },
      { description: 'Metal Roofing Screws (with washers)', quantity: 12, unit: 'box', unitPrice: 45, total: 540 },
      { description: 'Pipe Flashings (metal)', quantity: 6, unit: 'ea', unitPrice: 65, total: 390 },
      { description: 'Butyl Sealant Tape', quantity: 8, unit: 'roll', unitPrice: 25, total: 200 },
      { description: 'Labor - Installation', quantity: 25, unit: 'sq', unitPrice: 220, total: 5500 },
      { description: 'Dumpster & Cleanup', quantity: 1, unit: 'ea', unitPrice: 450, total: 450 },
    ],
    terms: '50% deposit required. Balance due upon completion. Warranty: 10-year workmanship, 40-year paint warranty.',
    notes: 'Price based on 2,500 sqft roof. Metal roofing is durable, energy-efficient, and low maintenance. Color options available.',
  },
  {
    id: 'standing-seam-metal',
    name: 'Standing Seam Metal Roof',
    description: 'Premium standing seam metal roofing system',
    category: 'roofing',
    items: [
      { description: 'Roof Tear-Off & Disposal (if needed)', quantity: 25, unit: 'sq', unitPrice: 125, total: 3125 },
      { description: 'Standing Seam Metal Panels (24 gauge)', quantity: 2600, unit: 'sqft', unitPrice: 8.5, total: 22100 },
      { description: 'High-Temp Underlayment', quantity: 25, unit: 'sq', unitPrice: 65, total: 1625 },
      { description: 'Metal Roof Clips (concealed fasteners)', quantity: 2600, unit: 'sqft', unitPrice: 0.75, total: 1950 },
      { description: 'Eave Trim (custom bent)', quantity: 180, unit: 'lf', unitPrice: 10, total: 1800 },
      { description: 'Rake Trim (custom bent)', quantity: 120, unit: 'lf', unitPrice: 10, total: 1200 },
      { description: 'Ridge Cap (standing seam)', quantity: 40, unit: 'lf', unitPrice: 25, total: 1000 },
      { description: 'Valley Panels (standing seam)', quantity: 30, unit: 'lf', unitPrice: 18, total: 540 },
      { description: 'Snow Guards (if required)', quantity: 50, unit: 'ea', unitPrice: 35, total: 1750 },
      { description: 'Pipe Flashings (custom)', quantity: 6, unit: 'ea', unitPrice: 125, total: 750 },
      { description: 'Butyl Sealant & Accessories', quantity: 1, unit: 'lot', unitPrice: 400, total: 400 },
      { description: 'Labor - Installation (specialized)', quantity: 25, unit: 'sq', unitPrice: 350, total: 8750 },
      { description: 'Seaming Tool Rental', quantity: 1, unit: 'ea', unitPrice: 800, total: 800 },
      { description: 'Dumpster & Cleanup', quantity: 1, unit: 'ea', unitPrice: 450, total: 450 },
    ],
    terms: '50% deposit required. Balance due upon completion. Warranty: 15-year workmanship, lifetime paint warranty.',
    notes: 'Price based on 2,500 sqft roof. Standing seam is the premium metal roofing option with superior weather protection and aesthetics. Requires specialized installation.',
  },
  {
    id: 'vinyl-siding',
    name: 'Vinyl Siding Installation',
    description: 'Complete vinyl siding replacement with trim',
    category: 'siding',
    items: [
      { description: 'Remove Old Siding & Disposal', quantity: 2000, unit: 'sqft', unitPrice: 1.5, total: 3000 },
      { description: 'Vinyl Siding Panels (0.046" thickness)', quantity: 2000, unit: 'sqft', unitPrice: 4.5, total: 9000 },
      { description: 'House Wrap (Tyvek or similar)', quantity: 2000, unit: 'sqft', unitPrice: 0.75, total: 1500 },
      { description: 'Insulated Backer Board (optional)', quantity: 2000, unit: 'sqft', unitPrice: 1.25, total: 2500 },
      { description: 'J-Channel (windows/doors)', quantity: 300, unit: 'lf', unitPrice: 2.5, total: 750 },
      { description: 'Outside Corner Posts', quantity: 12, unit: 'ea', unitPrice: 45, total: 540 },
      { description: 'Inside Corner Posts', quantity: 8, unit: 'ea', unitPrice: 40, total: 320 },
      { description: 'Starter Strip', quantity: 200, unit: 'lf', unitPrice: 1.5, total: 300 },
      { description: 'Fascia Trim (vinyl)', quantity: 180, unit: 'lf', unitPrice: 6, total: 1080 },
      { description: 'Soffit Panels (vented)', quantity: 400, unit: 'sqft', unitPrice: 3.5, total: 1400 },
      { description: 'Soffit F-Channel', quantity: 200, unit: 'lf', unitPrice: 2, total: 400 },
      { description: 'Utility Trim & Accessories', quantity: 1, unit: 'lot', unitPrice: 350, total: 350 },
      { description: 'Nails & Fasteners', quantity: 1, unit: 'lot', unitPrice: 200, total: 200 },
      { description: 'Labor - Installation', quantity: 2000, unit: 'sqft', unitPrice: 3.5, total: 7000 },
      { description: 'Dumpster & Cleanup', quantity: 1, unit: 'ea', unitPrice: 350, total: 350 },
    ],
    terms: '40% deposit required. Balance due upon completion. Warranty: Lifetime limited manufacturer warranty, 5-year workmanship.',
    notes: 'Price based on 2,000 sqft of siding. Vinyl siding is low-maintenance and cost-effective. Multiple colors available. Does not include window/door replacement.',
  },
  {
    id: 'aluminum-siding',
    name: 'Aluminum Siding Installation',
    description: 'Aluminum siding system with trim and accessories',
    category: 'siding',
    items: [
      { description: 'Remove Old Siding & Disposal', quantity: 2000, unit: 'sqft', unitPrice: 1.5, total: 3000 },
      { description: 'Aluminum Siding Panels (0.019" gauge)', quantity: 2000, unit: 'sqft', unitPrice: 5.5, total: 11000 },
      { description: 'House Wrap (weather barrier)', quantity: 2000, unit: 'sqft', unitPrice: 0.75, total: 1500 },
      { description: 'Rigid Foam Insulation (1" R-5)', quantity: 2000, unit: 'sqft', unitPrice: 1.5, total: 3000 },
      { description: 'Aluminum J-Channel', quantity: 300, unit: 'lf', unitPrice: 3.5, total: 1050 },
      { description: 'Aluminum Outside Corners', quantity: 12, unit: 'ea', unitPrice: 55, total: 660 },
      { description: 'Aluminum Inside Corners', quantity: 8, unit: 'ea', unitPrice: 50, total: 400 },
      { description: 'Starter Strip (aluminum)', quantity: 200, unit: 'lf', unitPrice: 2, total: 400 },
      { description: 'Aluminum Fascia (coil stock)', quantity: 180, unit: 'lf', unitPrice: 8, total: 1440 },
      { description: 'Aluminum Soffit (vented)', quantity: 400, unit: 'sqft', unitPrice: 4.5, total: 1800 },
      { description: 'Soffit F-Channel (aluminum)', quantity: 200, unit: 'lf', unitPrice: 2.5, total: 500 },
      { description: 'Trim Coil & Accessories', quantity: 1, unit: 'lot', unitPrice: 450, total: 450 },
      { description: 'Aluminum Nails & Fasteners', quantity: 1, unit: 'lot', unitPrice: 250, total: 250 },
      { description: 'Labor - Installation', quantity: 2000, unit: 'sqft', unitPrice: 4, total: 8000 },
      { description: 'Dumpster & Cleanup', quantity: 1, unit: 'ea', unitPrice: 350, total: 350 },
    ],
    terms: '40% deposit required. Balance due upon completion. Warranty: 20-year paint warranty, 5-year workmanship.',
    notes: 'Price based on 2,000 sqft of siding. Aluminum siding is durable, fire-resistant, and paintable. Factory-baked enamel finish available in multiple colors.',
  },
];

export const getTemplatesByCategory = (category: EstimateTemplate['category']) => {
  return ESTIMATE_TEMPLATES.filter(t => t.category === category);
};

export const getTemplateById = (id: string) => {
  return ESTIMATE_TEMPLATES.find(t => t.id === id);
};
